# Generated by Django 4.2.5 on 2023-09-11 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the Project.', max_length=50)),
                ('lead', models.CharField(help_text='Team lead name', max_length=50)),
                ('dateStarted', models.DateTimeField(help_text='Date and time project was created', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Label of the task', max_length=50)),
                ('description', models.TextField(help_text='Task description')),
                ('complete', models.BooleanField(default=False, help_text='Task completed or not')),
            ],
        ),
    ]
